### ISSUE TITLE
Rebase merge strategy

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#201]
Why do we use rebase merge strategy in this repository? Don't we lose commit history by using it?

**Comment by jb3** [comment]
No, whilst we are rebasing we are not squashing. It is effectively taking the commits and placing them onto the HEAD of the main branch. The downside is that we're required to ensure branches are up to date before merging as we cannot have merge commits anywhere. Essentially, we end up with a repository history that is as linear as possible, not dissimilar to a fast-forward merge.

If we branch off and have something like this:

```
          A -- B -- C (master)
                 \
                  D -- E -- F (feature)
```

When we merge it back in, we ensure the branch is up to date with `master`, and get a resulting Git history like this:

```
                   A -- B -- C -- D' -- E' -- F' (master)
```

As long as the branches are up to date, we maintain all authorship info (which is why it is advisory to update branches locally rather than having GitHub do a rebase update).

**Comment by jchristgit** [comment]
Thanks, this makes sense to me.
