### ISSUE TITLE
Retiring GitHub merge commits

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#357]
Unfortunately we keep experiencing incidents where our repository's security is
impaired due to people merging over the GitHub UI.

We should find a way to block any merge commits over the GitHub UI to enforce
local merging that is cryptograhically validated by a team member's PGP key.

Perhaps the `policy-bot` can be used for this.

**Comment by jb3** [comment]
I agree with this in principle.

I do not however see a way to nicely implement this onto our repositories. We
can have a policy-bot check that always fails/stays as pending and just prevent
the GitHub UI merge button from ever turning "green".

This approach works but means we lose visibility into quickly glancing at the
status of pull requests and looking at the other checks.

The other approach to simplify things without doing a local merge is creating a
GitHub Bot that is capable of performing fast-forward merges like we are aiming
to require here. This could be triggered from GitHub or Discord and ensure that
a selection of pre-conditions are met *without* otherwise compromising the PR
statuses on GitHub.

What are your thoughts regarding which approach to take? I know a GitHub bot is
a convoluted way of achieving this but once setup it a) should continue to work
as it's only doing fast-forward merges and b) presents the nicest UX to the end
user.

**Comment by jb3** [comment]
> How would that work? Like, how does a bot not have the same signature issues?

The bot would have to use some sort of git-wrapper to clone a temporary copy of
the repository, it could not do it through the API as GitHub does not support
fast-forward merges at all.

It would have to clone the repository, check the branch it's merging is up to
date (we *can* use the API for this). Then do the fast-forward and push it.

Fast-forwards do not do any sort of rewriting, hence I believe the original
signatures would remain valid (this is why our local merge and pushes work
fine).

**Comment by jb3** [comment]
I think this is more or less done now?
