### ISSUE TITLE
Redis brownouts

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#430]
As DevOps we should constnatly be looking out for ways to improve our resiliency.

We currently have a bit of a strange situation with Redis. Whilst the understanding within the DevOps team is generally that Redis is a cache and as such should be treated as transient, unfortunately our applications have now often been built with the assumption that Redis is always present and available. When we do need to take it offline or it migrates elsewhere for some reason, the amount of errors we receive is usually very high.

I propose we add a regularly scheduled downtime for Redis to ensure that applications can function with Redis not being available. I am not suggesting major downtime, just something like five minutes at 3 AM every month that is large enough to hopefully showcase some problems, but small enough to not cause widespread problems.

We would clearly announce this to staff to be aware of and give 1-2 months notice before the first downtime happens, and obviously I regard it as our duty to help our devs out where we can.

I think this would be a good strategy for other services as well, just Redis is the only one we currently rely on like this that comes to mind.

**Comment by jb3** [comment]
> Whilst the understanding within the DevOps team is generally that Redis is a cache and as such should be treated as transient

I don't think this is the case, I think this is what the DevOps team would _like_ but we do take every measure we can to ensure persistency, and with the Redis options configured as we do, Redis _is_ fairly persistent. We have had Redis losses before and it is annoying but it was not bad then and even now it wouldn't be too bad.

We can make services resilience against Redis _downtime_, I think that is a better focus than a war on persistency.

> We would clearly announce this to staff to be aware of and give 1-2 months notice before the first downtime happens, and obviously I regard it as our duty to help our devs out where we can.

This won't affect staff, and staff will not be in a position to change. If we are changing the environment, DevOps need to be the ones to make the amendments to the services to handle the changes.

We do not work in an organisation where teams are expected to deal with unilateral changes by other components of the organisation, we have complete authority here and I don't think it is reasonable to expect Staff or Core Developers to make large amendments to our software because we have a grudge against Redis, it is a sure-fire way to burnout our team.
